# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CurvaDeNivel
                                 A QGIS plugin
 Cria curvas de nivel a partir de dados geomorféticos do INPE
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-08
        copyright            : (C) 2024 by Daniel Hulshof Saint Martin
        email                : daniel.hulshof@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Daniel Hulshof Saint Martin'
__date__ = '2024-10-08'
__copyright__ = '(C) 2024 by Daniel Hulshof Saint Martin'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import math
import os
import re
import shutil
import urllib.error
import urllib.request
from urllib.parse import urlparse
import zipfile
import tempfile
from osgeo import gdal, ogr, osr
from .gdal_calc import Calc
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    Qgis,
    QgsApplication,
    QgsAuthMethodConfig,
    QgsCoordinateReferenceSystem,
    QgsGeometry,
    QgsPalLayerSettings,
    QgsPointXY,
    QgsProcessingAlgorithm,
    QgsProcessingParameterAuthConfig,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterExtent,
    QgsProcessingParameterNumber,
    QgsProcessingParameterColor,
    QgsProcessingParameterEnum,
    QgsProject,
    QgsRasterLayer,
    QgsRuleBasedRenderer,
    QgsSymbol,
    QgsSymbolLayerReference,
    QgsSymbolLayerId,
    QgsTextMaskSettings,
    QgsTextFormat,
    QgsVectorLayer,
    QgsVectorLayerSimpleLabeling
)

# URL base do Copernicus GLO-30 DEM (AWS Open Data, sem autenticação)
# https://registry.opendata.aws/copernicus-dem/
COPERNICUS_BASE_URL = 'https://copernicus-dem-30m.s3.amazonaws.com/'


'''
    TODO:

    Adicionar suavização das curvas de nivel. Ferramentas necessárias:
    - gdal_translate
    - gdaldem
    - gdalbuildvrt
    - gdalinfo
    - gdal_calc.py
    - gdal_contour
    - ogr2ogr

'''


class CurvaDeNivelAlgorithm(QgsProcessingAlgorithm):

    # Define constantes
    AREA_INTERESSE = 'AREA_INTERESSE'
    FONTE_DEM = 'FONTE_DEM'
    INTERVALO = 'INTERVALO'
    SUAVIZACAO = 'SUAVIZACAO'
    COR_CURVAS = 'COR_CURVAS'
    ELEVATION_MAP = 'ELEVATION_MAP'
    AUTENTIC = 'AUTENTIC'

    def __init__(self):
        super().__init__()
        # Caminho da pasta de armazenamento temporário
        self.temp_dir = os.path.join(tempfile.gettempdir(), 'CurvaDeNivel')
        self.status_total = 0.0
        self.progresso = 0.0

    def flags(self):
        if Qgis.QGIS_VERSION_INT >= 40000:
            return super().flags() | Qgis.ProcessingAlgorithmFlag.NoThreading
        else:
            return super().flags() | QgsProcessingAlgorithm.FlagNoThreading

    def initAlgorithm(self, config):

        # Adiciona entrada da área de interesse
        self.addParameter(
            QgsProcessingParameterExtent(
                self.AREA_INTERESSE,
                "Área de Interesse (selecionar)",
                optional=False))

        # Adiciona seleção da fonte de DEM
        self.addParameter(
            QgsProcessingParameterEnum(
                name=self.FONTE_DEM,
                description=self.tr('Fonte de dados de elevação'),
                options=['INPE TOPODATA (Brasil)', 'Copernicus GLO-30 (Mundial)'],
                defaultValue=0,
                optional=False
            )
        )

        # Adiciona intervalo entre curvas
        self.addParameter(
            QgsProcessingParameterNumber(
                name=self.INTERVALO,
                description=self.tr('Intervalo entre curvas'),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=10,
                minValue=1,
                maxValue=1000,
                optional=False
            )
        )

        # Adiciona nível de suavização
        self.addParameter(
            QgsProcessingParameterEnum(
                name=self.SUAVIZACAO,
                description=self.tr('Nível de suavização das curvas'),
                options=['Nenhum', 'Baixo', 'Médio', 'Alto'],
                defaultValue='Médio',
                usesStaticStrings=True,
                optional=False
            )
        )

        # Adiciona cor da curva de nivel
        self.addParameter(
            QgsProcessingParameterColor(
                name=self.COR_CURVAS,
                description=self.tr('Coloração das curvas'),
                defaultValue="#cc7700cc",
                opacityEnabled=True,
                optional=False
            )
        )

        # Adiciona opção de overlay de elevação
        self.addParameter(
            QgsProcessingParameterBoolean(
                name=self.ELEVATION_MAP,
                description=self.tr('Gerar Overlay de Elevação (Hillshade)'),
                defaultValue=True,
                optional=False
            )
        )

        # Adiciona autenticação
        self.addParameter(
            QgsProcessingParameterAuthConfig(
                name=self.AUTENTIC,
                description=self.tr('Usar autenticação de Proxy'),
                optional=True
            )
        )

    def processAlgorithm(self, parameters, context, feedback):

        # Cria pasta temporário para armazenar arquivos
        self.status_total = 0.0
        self.progresso = 0.0
        os.makedirs(self.temp_dir, exist_ok=True)
        feedback.pushInfo('\nAbrindo pasta temporária: ' + self.temp_dir)

        # Carrega poligono da area de interesse e cria shapefile temporario
        area_interesse = self.parameterAsExtent(
            parameters,
            self.AREA_INTERESSE,
            context,
            crs=QgsCoordinateReferenceSystem("EPSG:4326"))

        # Valida se a área de interesse é válida
        if area_interesse.isNull() or not area_interesse.isFinite():
            raise ValueError(
                self.tr(
                    'Área de interesse inválida (valores NaN detectados).\n\n'
                    'Isso pode ocorrer quando:\n'
                    '- Uma camada de polígono é selecionada mas não foi salva\n'
                    '- A camada está vazia ou não tem geometrias válidas\n\n'
                    'Por favor:\n'
                    '1. Desenhe um retângulo diretamente usando a ferramenta de extent, OU\n'
                    '2. Se usar uma camada de polígono, certifique-se de salvá-la primeiro'))

        geometria_area_interesse = QgsGeometry.fromRect(area_interesse)

        # Valida se a geometria foi criada com sucesso
        if geometria_area_interesse.isNull() or geometria_area_interesse.isEmpty():
            raise ValueError(
                self.tr('Não foi possível criar a geometria da área de interesse.'))

        caminho_shp_area_interesse = os.path.join(
            self.temp_dir, 'area_interesse.shp')
        shp_driver = ogr.GetDriverByName("ESRI Shapefile")
        if os.path.exists(caminho_shp_area_interesse):
            shp_driver.DeleteDataSource(caminho_shp_area_interesse)
        shp_area_interesse = shp_driver.CreateDataSource(
            caminho_shp_area_interesse)
        layer_area_interesse = shp_area_interesse.CreateLayer(
            "layer", geom_type=ogr.wkbPolygon)
        featureDefn = layer_area_interesse.GetLayerDefn()
        feature = ogr.Feature(featureDefn)

        # Converte a geometria QGIS para WKT e cria a geometria OGR
        wkt_geometria = geometria_area_interesse.asWkt()
        ogr_geometria = ogr.CreateGeometryFromWkt(wkt_geometria)

        if ogr_geometria is None:
            raise ValueError(self.tr(
                'Erro ao converter a geometria para o formato OGR. WKT: {}').format(wkt_geometria))

        feature.SetGeometry(ogr_geometria)
        layer_area_interesse.CreateFeature(feature)
        shp_area_interesse = None

        # Carrega o intervalo entre as curvas de nível
        intervalo = self.parameterAsInt(parameters, self.INTERVALO, context)

        # Carrega a opção de suavização das curvas
        suavizar = self.parameterAsString(parameters, self.SUAVIZACAO, context)

        # Carrega a cor das curvas de nível
        cor_curva = self.parameterAsColor(parameters, self.COR_CURVAS, context)

        # Carrega a opção de gerar overlay de elevação
        gerar_mapa_elevacao = self.parameterAsBool(parameters, self.ELEVATION_MAP, context)

        # Carrega a fonte de DEM selecionada (0 = INPE, 1 = Copernicus)
        fonte_dem = self.parameterAsEnum(parameters, self.FONTE_DEM, context)

        # Carrega dados de autenticação para proxy
        proxy_opener = None
        autentic = self.parameterAsString(parameters, self.AUTENTIC, context)
        if (autentic == ''):
            feedback.pushInfo('\nSem autenticação de proxy')
        else:
            auth_mgr = QgsApplication.authManager()
            auth_cfg = QgsAuthMethodConfig()
            auth_mgr.loadAuthenticationConfig(autentic, auth_cfg, True)
            auth_info = auth_cfg.configMap()
            try:
                proxy_host = urlparse(auth_info['realm']).hostname
                proxy_port = urlparse(auth_info['realm']).port
                proxy_user = auth_info['username']
                proxy_pass = auth_info['password']
                proxy_base_url = 'http://{}:{}'.format(proxy_host, proxy_port)
                proxy_mgr = urllib.request.HTTPPasswordMgrWithDefaultRealm()
                proxy_mgr.add_password(
                    None, proxy_base_url, proxy_user, proxy_pass)
                proxy_auth_handler = urllib.request.ProxyBasicAuthHandler(
                    proxy_mgr)
                proxy_handler = urllib.request.ProxyHandler(
                    {'http': proxy_base_url, 'https': proxy_base_url})
                proxy_opener = urllib.request.build_opener(
                    proxy_handler, proxy_auth_handler)
                feedback.pushInfo(
                    '\nUtilizando autenticação de proxy para usuário: '
                    + proxy_user)
            except Exception as e:
                feedback.pushInfo(
                    '\nErro ao carregar dados de autenticação de proxy: ' + str(e))

        # Define callback da biblioteca gdal
        def callback_gdal(info, *args):
            progresso_warp = self.progresso + info
            feedback.setProgress(int(progresso_warp * self.status_total))

        # ------------------------------------------------------------------ #
        # Descobre e baixa tiles da fonte de DEM selecionada                  #
        # ------------------------------------------------------------------ #
        if fonte_dem == 0:
            # ---- INPE TOPODATA (cobre apenas o Brasil) ------------------- #
            caminho_raster = 'http://www.dsr.inpe.br/topodata/data/geotiff/'
            lista_rasters = []
            lat_norte = 6.0
            lon_oeste = -75.0

            feedback.pushInfo('\nCalculando arquivos raster necessários (INPE TOPODATA)')
            while (lat_norte > -34.0):
                lon_oeste = -75.0
                while (lon_oeste < -34.5):
                    points = [
                        QgsPointXY(lon_oeste, lat_norte),
                        QgsPointXY(lon_oeste + 1.5, lat_norte),
                        QgsPointXY(lon_oeste + 1.5, lat_norte - 1.0),
                        QgsPointXY(lon_oeste, lat_norte - 1.0)]
                    poly = QgsGeometry.fromPolygonXY([points])
                    if not poly.intersection(geometria_area_interesse).isEmpty():
                        nome_raster = list("00S00_ZN")
                        nome_raster[0] = str(abs(int(lat_norte / 10)))
                        nome_raster[1] = str(abs(int(lat_norte)) % 10)
                        if lat_norte > 0:
                            nome_raster[2] = 'N'
                        nome_raster[3] = str(abs(int(lon_oeste / 10)))
                        nome_raster[4] = str(abs(int(lon_oeste)) % 10)
                        if lon_oeste % 1.0 == 0:
                            nome_raster[5] = '_'
                        else:
                            nome_raster[5] = '5'
                        if ''.join(nome_raster) not in lista_rasters:
                            lista_rasters.append(''.join(nome_raster))
                            feedback.pushInfo(
                                'Arquivo necessário: ' + ''.join(nome_raster) + '.tif')
                    lon_oeste += 1.5
                lat_norte -= 1.0

            if not lista_rasters:
                feedback.pushInfo(
                    '\nNenhum arquivo raster encontrado para a área selecionada.'
                    '\nA base de dados TOPODATA do INPE cobre apenas o território brasileiro.'
                    '\nCobertura: lat -34°S a 6°N, lon -75°O a -34°O'
                    '\nVerifique se a área de interesse está dentro do Brasil.')
                return {}

            numeroDeEtapas = 5 + 2 * len(lista_rasters)
            self.status_total = 100.0 / numeroDeEtapas
            self.progresso = 0.0
            self.progresso += 1
            feedback.setProgress(int(self.progresso * self.status_total))

            for raster in lista_rasters[:]:
                if feedback.isCanceled():
                    feedback.pushInfo('\nCancelado pelo usuário')
                    return {}
                feedback.pushInfo('\nBuscando arquivo Raster: ' + raster + '.tif')
                if os.path.exists(os.path.join(self.temp_dir, raster + '.tif')):
                    feedback.pushInfo('Arquivo localizado no disco')
                else:
                    feedback.pushInfo('Baixando arquivo raster: ' + raster + '.zip')
                    raster_url = caminho_raster + raster + '.zip'
                    try:
                        opener = proxy_opener if proxy_opener else urllib.request.build_opener()
                        with opener.open(raster_url, timeout=30) as response:
                            total_size = int(response.headers.get('Content-Length', 0))
                            chunks = []
                            bytes_received = 0
                            chunk_size = 65536
                            while True:
                                chunk = response.read(chunk_size)
                                if not chunk:
                                    break
                                chunks.append(chunk)
                                bytes_received += len(chunk)
                                if total_size > 0:
                                    progresso_download = self.progresso + bytes_received / total_size
                                    feedback.setProgress(
                                        int(progresso_download * self.status_total))
                            content = b''.join(chunks)
                        if content:
                            with tempfile.TemporaryFile() as zip:
                                zip.write(content)
                                with zipfile.ZipFile(zip) as zf:
                                    files = zf.namelist()
                                    for filename in files:
                                        feedback.pushInfo(
                                            'Descompactando arquivo: ' + filename)
                                        file_path = os.path.join(self.temp_dir, filename)
                                        with open(file_path, 'wb') as f:
                                            f.write(zf.read(filename))
                        else:
                            raise ValueError('Resposta vazia do servidor')
                    except Exception as e:
                        feedback.pushInfo('\nErro ao baixar o arquivo: ' + raster_url)
                        feedback.pushInfo('\nVerifique o proxy ou a conexão com a internet')
                        feedback.pushInfo(
                            '\nCopie e cole o link acima no navegador para testar manualmente')
                        feedback.pushInfo('\nDetalhe do erro: ' + str(e))
                        lista_rasters.remove(raster)
                self.progresso += 1
                feedback.setProgress(int(self.progresso * self.status_total))

            if not lista_rasters:
                feedback.pushInfo(
                    '\nErro ao baixar os arquivos raster.'
                    '\nTodos os arquivos necessários falharam no download.'
                    '\nVerifique a conexão com a internet ou o proxy e tente novamente.')
                return {}

            feedback.pushInfo('\nRecortando arquivos raster pela área de interesse')
            raster_clips = []
            for raster in lista_rasters:
                fn_in = os.path.join(self.temp_dir, raster + '.tif')
                fn_clip = os.path.join(self.temp_dir, raster + '_clip.tif')
                raster_clips.append(fn_clip)
                feedback.pushInfo('Recortando: ' + raster + '.tif')
                gdal.Warp(
                    fn_clip,
                    fn_in,
                    cutlineDSName=caminho_shp_area_interesse,
                    cropToCutline=True,
                    dstNodata=0,
                    srcSRS='EPSG:4326',
                    dstSRS='EPSG:4326',
                    format='GTiff',
                    callback=callback_gdal)
                if feedback.isCanceled():
                    feedback.pushInfo('\nCancelado pelo usuário')
                    return {}
                self.progresso += 1
                feedback.setProgress(int(self.progresso * self.status_total))

            if not raster_clips:
                feedback.pushInfo('\nNenhum arquivo foi recortado com sucesso.')
                return {}

            feedback.pushInfo('\nJuntando arquivos raster recortados pela área de interesse')
            gdal.Warp(
                os.path.join(self.temp_dir, 'merged.tif'),
                raster_clips,
                format='GTiff',
                callback=callback_gdal)

            if feedback.isCanceled():
                feedback.pushInfo('\nCancelado pelo usuário')
                return {}

            self.progresso += 1
            feedback.setProgress(int(self.progresso * self.status_total))

        else:
            # ---- Copernicus GLO-30 (AWS Open Data, worldwide) ------------ #
            south = area_interesse.yMinimum()
            north = area_interesse.yMaximum()
            west = area_interesse.xMinimum()
            east = area_interesse.xMaximum()

            tile_list = []
            feedback.pushInfo('\nCalculando tiles Copernicus GLO-30 necessários')
            for lat in range(math.floor(south), math.ceil(north)):
                for lon in range(math.floor(west), math.ceil(east)):
                    tile_points = [
                        QgsPointXY(lon, lat),
                        QgsPointXY(lon + 1, lat),
                        QgsPointXY(lon + 1, lat + 1),
                        QgsPointXY(lon, lat + 1)]
                    tile_poly = QgsGeometry.fromPolygonXY([tile_points])
                    if tile_poly.intersection(geometria_area_interesse).isEmpty():
                        continue
                    ns = 'N' if lat >= 0 else 'S'
                    ew = 'E' if lon >= 0 else 'W'
                    tile_name = 'Copernicus_DSM_COG_10_{}{:02d}_00_{}{:03d}_00_DEM'.format(
                        ns, abs(lat), ew, abs(lon))
                    if tile_name not in tile_list:
                        tile_list.append(tile_name)
                        feedback.pushInfo('Tile necessário: ' + tile_name)

            if not tile_list:
                feedback.pushInfo('\nNenhum tile Copernicus encontrado para a área selecionada.')
                return {}

            numeroDeEtapas = 5 + 2 * len(tile_list)
            self.status_total = 100.0 / numeroDeEtapas
            self.progresso = 0.0
            self.progresso += 1
            feedback.setProgress(int(self.progresso * self.status_total))

            for tile_name in tile_list[:]:
                if feedback.isCanceled():
                    feedback.pushInfo('\nCancelado pelo usuário')
                    return {}
                local_tif = os.path.join(self.temp_dir, tile_name + '.tif')
                feedback.pushInfo('\nBuscando tile: ' + tile_name + '.tif')
                if os.path.exists(local_tif):
                    feedback.pushInfo('Tile localizado no disco')
                else:
                    tile_url = '{}{}/{}.tif'.format(
                        COPERNICUS_BASE_URL, tile_name, tile_name)
                    feedback.pushInfo('Baixando: ' + tile_url)
                    try:
                        opener = proxy_opener if proxy_opener else urllib.request.build_opener()
                        with opener.open(tile_url, timeout=60) as response:
                            total_size = int(response.headers.get('Content-Length', 0))
                            chunks = []
                            bytes_received = 0
                            chunk_size = 65536
                            while True:
                                chunk = response.read(chunk_size)
                                if not chunk:
                                    break
                                chunks.append(chunk)
                                bytes_received += len(chunk)
                                if total_size > 0:
                                    progresso_download = self.progresso + bytes_received / total_size
                                    feedback.setProgress(
                                        int(progresso_download * self.status_total))
                            content = b''.join(chunks)
                        if content:
                            with open(local_tif, 'wb') as f:
                                f.write(content)
                        else:
                            raise ValueError('Resposta vazia do servidor')
                    except urllib.error.HTTPError as e:
                        if e.code == 404:
                            feedback.pushInfo(
                                'AVISO: Tile não disponível (HTTP 404) — '
                                'pode ser área oceânica ou tile restrito: ' + tile_name)
                        else:
                            feedback.pushInfo('\nErro HTTP ao baixar tile: ' + str(e))
                            feedback.pushInfo('URL: ' + tile_url)
                        tile_list.remove(tile_name)
                    except Exception as e:
                        feedback.pushInfo('\nErro ao baixar tile: ' + tile_url)
                        feedback.pushInfo(
                            '\nVerifique o proxy ou a conexão com a internet')
                        feedback.pushInfo('\nDetalhe do erro: ' + str(e))
                        tile_list.remove(tile_name)
                self.progresso += 1
                feedback.setProgress(int(self.progresso * self.status_total))

            if not tile_list:
                feedback.pushInfo('\nNenhum tile foi baixado com sucesso.')
                return {}

            feedback.pushInfo('\nRecortando tiles pela área de interesse')
            raster_clips = []
            for tile_name in tile_list:
                fn_in = os.path.join(self.temp_dir, tile_name + '.tif')
                fn_clip = os.path.join(self.temp_dir, tile_name + '_clip.tif')
                raster_clips.append(fn_clip)
                feedback.pushInfo('Recortando: ' + tile_name + '.tif')
                gdal.Warp(
                    fn_clip,
                    fn_in,
                    cutlineDSName=caminho_shp_area_interesse,
                    cropToCutline=True,
                    dstNodata=-32768,
                    srcSRS='EPSG:4326',
                    dstSRS='EPSG:4326',
                    format='GTiff',
                    callback=callback_gdal)
                if feedback.isCanceled():
                    feedback.pushInfo('\nCancelado pelo usuário')
                    return {}
                self.progresso += 1
                feedback.setProgress(int(self.progresso * self.status_total))

            if not raster_clips:
                feedback.pushInfo('\nNenhum tile foi recortado com sucesso.')
                return {}

            feedback.pushInfo('\nJuntando tiles recortados pela área de interesse')
            gdal.Warp(
                os.path.join(self.temp_dir, 'merged.tif'),
                raster_clips,
                dstNodata=-32768,
                format='GTiff',
                callback=callback_gdal)

            if feedback.isCanceled():
                feedback.pushInfo('\nCancelado pelo usuário')
                return {}

            self.progresso += 1
            feedback.setProgress(int(self.progresso * self.status_total))

        # ------------------------------------------------------------------ #
        # Processamento comum: suavização, curvas de nível, simbologia        #
        # ------------------------------------------------------------------ #

        # Guarda cópia do DEM antes da suavização para o overlay de elevação
        elevation_dem_path = os.path.join(self.temp_dir, 'elevation.tif')
        shutil.copy2(os.path.join(self.temp_dir, 'merged.tif'), elevation_dem_path)

        # Faz suavização
        self.suavizaTerreno(suavizar, feedback)

        if feedback.isCanceled():
            feedback.pushInfo('\nCancelado pelo usuário')
            return {}

        # Atualiza progresso e barra
        self.progresso += 1
        feedback.setProgress(int(self.progresso * self.status_total))

        # Gera as curvas de nível a partir da imagem unificada
        feedback.pushInfo('\nGerando curvas de nível')
        tmp_shp_dir = tempfile.mkdtemp(dir=self.temp_dir, prefix='curvasdenivel_')
        caminho_shp_temp = os.path.join(tmp_shp_dir, 'curvasdenivel.shp')
        shp_temp = shp_driver.CreateDataSource(caminho_shp_temp)
        srs_4326 = osr.SpatialReference()
        srs_4326.ImportFromEPSG(4326)
        srs_4326.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)
        layer_temp = shp_temp.CreateLayer('Curvas De Nivel', srs=srs_4326)
        layer_temp.CreateField(ogr.FieldDefn('ID', ogr.OFTInteger))
        layer_temp.CreateField(ogr.FieldDefn('ELEV', ogr.OFTReal))
        field_defn = ogr.FieldDefn('TYPE', ogr.OFTString)
        field_defn.SetWidth(50)
        layer_temp.CreateField(field_defn)
        raster_merged = gdal.Open(os.path.join(self.temp_dir, 'merged.tif'))
        merged_band = raster_merged.GetRasterBand(1)
        nodata_val = merged_band.GetNoDataValue()
        gdal.ContourGenerate(
            merged_band,
            intervalo,
            0,
            [],
            1 if nodata_val is not None else 0,
            nodata_val if nodata_val is not None else 0,
            layer_temp,
            0,
            1,
            callback=callback_gdal)
        shp_temp = None
        raster_merged = None

        if feedback.isCanceled():
            feedback.pushInfo('\nCancelado pelo usuário')
            return {}

        # Atualiza progresso e barra
        self.progresso += 1
        feedback.setProgress(int(self.progresso * self.status_total))

        # Reprojecta para o CRS do projeto se necessário
        project_crs = context.project().crs()
        if project_crs.isValid() and project_crs.authid().upper() != 'EPSG:4326':
            feedback.pushInfo('\nReprojectando curvas para ' + project_crs.authid())
            tmp_reproj_dir = tempfile.mkdtemp(
                dir=self.temp_dir, prefix='curvasdenivel_reproj_')
            caminho_shp_reproj = os.path.join(
                tmp_reproj_dir, 'curvasdenivel_reproj.shp')
            gdal.VectorTranslate(
                caminho_shp_reproj,
                caminho_shp_temp,
                options=gdal.VectorTranslateOptions(
                    dstSRS=project_crs.authid(),
                    reproject=True))
            caminho_shp_final = caminho_shp_reproj
        else:
            caminho_shp_final = caminho_shp_temp

        # Carrega camada de curvas de nível
        layer = QgsVectorLayer(caminho_shp_final, 'Curvas De Nivel')
        feedback.pushInfo('Numero de curvas geradas: ' + str(len(list(layer.getFeatures()))))

        # Modifica a simbologia
        layer_curvas = layer
        symbol = QgsSymbol.defaultSymbol(layer_curvas.geometryType())
        renderer = QgsRuleBasedRenderer(symbol)
        root_rule = renderer.rootRule()

        # Curva Mestra
        rule = root_rule.children()[0]
        rule.setLabel('Curva Mestra')
        rule.setFilterExpression(f'"ELEV" % {intervalo*5} = 0')
        rule.symbol().setColor(cor_curva)
        rule.symbol().setWidth(0.5)

        # Curva Normal
        rule = root_rule.children()[0].clone()
        rule.setLabel('Curva Normal')
        rule.setFilterExpression('ELSE')
        rule.symbol().setColor(cor_curva)
        rule.symbol().setWidth(0.25)
        root_rule.appendChild(rule)

        layer_curvas.setRenderer(renderer)
        layer_curvas.triggerRepaint()

        # Cria os rótulos e máscara
        mask = QgsTextMaskSettings()
        mask.setSize(2)
        curva_mestra_rule = root_rule.children()[0]
        if Qgis.QGIS_VERSION_INT < 33000:
            mask.setMaskedSymbolLayers([QgsSymbolLayerReference(
                layer_curvas.id(), QgsSymbolLayerId(curva_mestra_rule.ruleKey(), 0))])
        else:
            mask.setMaskedSymbolLayers([QgsSymbolLayerReference(
                layer_curvas.id(), curva_mestra_rule.symbol().symbolLayer(0).id())])
        mask.setEnabled(True)

        textFormat = QgsTextFormat()
        textFormat.setSize(10)
        textFormat.setColor(cor_curva)
        textFormat.setMask(mask)

        settings = QgsPalLayerSettings()
        settings.fieldName = f'CASE WHEN "ELEV" % {intervalo*5} = 0 THEN "ELEV" ELSE \'\' END'
        settings.enabled = True
        settings.drawLabels = True
        settings.repeatDistance = 50
        settings.isExpression = True
        if Qgis.QGIS_VERSION_INT >= 40000:
            settings.placement = Qgis.LabelPlacementMode.Line
            settings.placementFlags = Qgis.LabelLinePlacementFlag.OnLine
        else:
            settings.placement = QgsPalLayerSettings.Line
            settings.placementFlags = QgsPalLayerSettings.OnLine
        settings.setFormat(textFormat)
        layer_curvas.setLabelsEnabled(True)
        layer_curvas.setLabeling(QgsVectorLayerSimpleLabeling(settings))
        layer_curvas.triggerRepaint()

        # Atualiza progresso e barra
        self.progresso += 1
        feedback.setProgress(int(self.progresso * self.status_total))

        feedback.pushInfo('\n')

        # Adiciona Elevation Overlay raster (inserido abaixo das curvas de nível)
        if gerar_mapa_elevacao:
            feedback.pushInfo('\nAdicionando camada de Elevation Overlay')

            qml_path = os.path.splitext(elevation_dem_path)[0] + '.qml'
            qml = (
                '<!DOCTYPE qgis PUBLIC \'http://mrcc.com/qgis.dtd\' \'SYSTEM\'>\n'
                '<qgis version="3.0" styleCategories="AllStyleCategories">\n'
                '  <pipe>\n'
                '    <provider>\n'
                '      <resampling enabled="true" maxOversampling="2"'
                ' zoomedInResamplingMethod="cubic"'
                ' zoomedOutResamplingMethod="cubic"/>\n'
                '    </provider>\n'
                '    <rasterrenderer type="hillshade" band="1" opacity="1"'
                ' alphaBand="-1" azimuth="315" angle="45"'
                ' multidirectionlighting="0" zFactor="1">\n'
                '      <rasterTransparency/>\n'
                '    </rasterrenderer>\n'
                '    <brightnesscontrast brightness="0" contrast="0" gamma="1"/>\n'
                '    <huesaturation saturation="0" grayscaleMode="0"'
                ' colorizeOn="0" colorizeRed="255" colorizeGreen="128"'
                ' colorizeBlue="128" colorizeStrength="100" invertColors="0"/>\n'
                '    <rasterresampler maxOversampling="2"'
                ' zoomedInResampler="cubic" zoomedOutResampler="cubic"/>\n'
                '  </pipe>\n'
                '  <blendMode>3</blendMode>\n'
                '</qgis>\n'
            )
            with open(qml_path, 'w', encoding='utf-8') as f:
                f.write(qml)
            feedback.pushInfo('QML gravado: ' + qml_path)

            dem_layer = QgsRasterLayer(elevation_dem_path, 'Elevação (Hillshade)')
            if dem_layer.isValid():
                QgsProject.instance().addMapLayer(dem_layer)
            else:
                feedback.pushInfo(
                    'Aviso: Não foi possível carregar a camada de Elevação (Hillshade)')

        # Adiciona camada ao projeto e retorna
        QgsProject.instance().addMapLayer(layer_curvas)
        return {}

    def suavizaTerreno(self, suavizar, feedback):
        # TODO: Adicionar progressão da barra de status

        if suavizar == 'Nenhum':
            return

        feedback.pushInfo('\nCalculando suavização')

        # Inicializa variáveis
        inputDEM = os.path.join(self.temp_dir, 'merged.tif')
        path = self.temp_dir  # Use apenas o diretório, sem barra extra

        # Gera tmp_dem.tif
        gdal.Translate(
            os.path.join(path, 'dem.tif'),
            inputDEM,
            options="-ot Float32 -a_nodata -32768"
        )

        # Constroi VRT 3x3
        gdal.BuildVRT(
            os.path.join(path, 'dem_blur_3x3.vrt'),
            os.path.join(path, 'dem.tif')
        )

        with open(os.path.join(path, "dem_blur_3x3.vrt"), "rt") as file:
            data = file.read()
        data = data.replace("ComplexSource", "KernelFilteredSource")
        data = data.replace(
            "<NODATA>-32768</NODATA>",
            '<NODATA>-32768</NODATA><Kernel normalized="1"><Size>3</Size><Coefs>0.077847 0.123317 0.077847 0.123317 0.195346 0.123317 0.077847 0.123317 0.077847</Coefs></Kernel>'
        )
        with open(os.path.join(path, "dem_blur_3x3.vrt"), "wt") as file:
            file.write(data)

        feedback.setProgress(int((self.progresso + 0.2) * self.status_total))

        # Calcula TPI
        gdal.DEMProcessing(
            destName=os.path.join(path, 'dem_tpi.tif'),
            srcDS=inputDEM,
            processing='TPI'
        )

        # Reclassifica TPI
        Calc(
            calc="((-1)*A*(A<0))+(A*(A>=0))",
            A=os.path.join(path, 'dem_tpi.tif'),
            outfile=os.path.join(path, 'tpi_pos.tif'),
            NoDataValue=-32768,
            overwrite=True
        )

        feedback.setProgress(int((self.progresso + 0.4) * self.status_total))

        # gera VRT do TPI
        gdal.BuildVRT(
            os.path.join(path, 'tpi_blur_3x3.vrt'),
            os.path.join(path, 'tpi_pos.tif')
        )

        with open(os.path.join(path, "tpi_blur_3x3.vrt"), "rt") as file:
            data = file.read()
        data = data.replace("ComplexSource", "KernelFilteredSource")
        data = data.replace(
            "<NODATA>-32768</NODATA>",
            '<NODATA>-32768</NODATA><Kernel normalized="1"><Size>9</Size><Coefs>0 0.000001 0.000014 0.000055 0.000088 0.000055 0.000014 0.000001 0 0.000001 0.000036 0.000362 0.001445 0.002289 0.001445 0.000362 0.000036 0.000001 0.000014 0.000362 0.003672 0.014648 0.023205 0.014648 0.003672 0.000362 0.000014 0.000055 0.001445 0.014648 0.058434 0.092566 0.058434 0.014648 0.001445 0.000055 0.000088 0.002289 0.023205 0.092566 0.146634 0.092566 0.023205 0.002289 0.000088 0.000055 0.001445 0.014648 0.058434 0.092566 0.058434 0.014648 0.001445 0.000055 0.000014 0.000362 0.003672 0.014648 0.023205 0.014648 0.003672 0.000362 0.000014 0.000001 0.000036 0.000362 0.001445 0.002289 0.001445 0.000362 0.000036 0.000001 0 0.000001 0.000014 0.000055 0.000088 0.000055 0.000014 0.000001 0</Coefs></Kernel>'
        )
        with open(os.path.join(path, "tpi_blur_3x3.vrt"), "wt") as file:
            file.write(data)

        feedback.setProgress(int((self.progresso + 0.6) * self.status_total))

        # Pega informações sobre o vrt do tpi
        vrt_path = os.path.join(path, 'tpi_blur_3x3.vrt')
        if not os.path.exists(vrt_path):
            raise FileNotFoundError(f"Arquivo não encontrado: {vrt_path}")
        info = gdal.Info(ds=vrt_path, options="-hist -stats")

        # Normaliza o vrt do tpi
        try:
            maxValue = re.findall(
                r'[0-9]*\.[0-9]*',
                re.findall(
                    r'STATISTICS_MAXIMUM=\d*\.\d*',
                    info)[0])[0]
            Calc(
                calc=f"A / {maxValue}",
                A=os.path.join(path, 'tpi_blur_3x3.vrt'),
                outfile=os.path.join(path, 'tpi_norm.tif'),
                NoDataValue=-32768,
                overwrite=True
            )
        except Exception:
            gdal.Translate(
                destName=os.path.join(path, 'tpi_norm.tif'),
                srcDS=os.path.join(path, 'tpi_blur_3x3.vrt')
            )

        feedback.setProgress(int((self.progresso + 0.8) * self.status_total))

        # Faz a suavização usando as entradas suavizadas e o TPI reclassificado
        if suavizar == "Baixo":
            Calc(
                calc="A*B+(1-A)*C",
                A=os.path.join(path, 'tpi_norm.tif'),
                B=os.path.join(path, 'dem_blur_3x3.vrt'),
                C=os.path.join(path, 'dem_blur_3x3.vrt'),
                outfile=os.path.join(path, 'merged.tif'),
                overwrite=True
            )
        elif suavizar == "Médio":
            # Constroi VRT 7x7
            gdal.BuildVRT(
                os.path.join(path, 'dem_blur_7x7.vrt'),
                os.path.join(path, 'dem.tif')
            )

            with open(os.path.join(path, "dem_blur_7x7.vrt"), "rt") as file:
                data = file.read()
            data = data.replace("ComplexSource", "KernelFilteredSource")
            data = data.replace(
                "<NODATA>-32768</NODATA>",
                '<NODATA>-32768</NODATA><Kernel normalized="1"><Size>7</Size><Coefs>0.000036 0.000363 0.001446 0.002291 0.001446 0.000363 0.000036 0.000363 0.003676 0.014662 0.023226 0.014662 0.003676 0.000363 0.001446 0.014662 0.058488 0.092651 0.058488 0.014662 0.001446 0.002291 0.023226 0.092651 0.146768 0.092651 0.023226 0.002291 0.001446 0.014662 0.058488 0.092651 0.058488 0.014662 0.001446 0.000363 0.003676 0.014662 0.023226 0.014662 0.003676 0.000363 0.000036 0.000363 0.001446 0.002291 0.001446 0.000363 0.000036</Coefs></Kernel>'
            )
            with open(os.path.join(path, "dem_blur_7x7.vrt"), "wt") as file:
                file.write(data)

            Calc(
                calc="A*B+(1-A)*C",
                A=os.path.join(path, 'tpi_norm.tif'),
                B=os.path.join(path, 'dem_blur_3x3.vrt'),
                C=os.path.join(path, 'dem_blur_7x7.vrt'),
                outfile=os.path.join(path, 'merged.tif'),
                overwrite=True
            )
        else:
            # Constroi VRT 13x13
            gdal.BuildVRT(
                os.path.join(path, 'dem_blur_13x13.vrt'),
                os.path.join(path, 'dem.tif')
            )

            with open(os.path.join(path, "dem_blur_13x13.vrt"), "rt") as file:
                data = file.read()
            data = data.replace("ComplexSource", "KernelFilteredSource")
            data = data.replace(
                "<NODATA>-32768</NODATA>",
                '<NODATA>-32768</NODATA><Kernel normalized="1"><Size>13</Size><Coefs>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.000001 0.000001 0.000001 0 0 0 0 0 0 0 0 0.000001 0.000014 0.000055 0.000088 0.000055 0.000014 0.000001 0 0 0 0 0.000014 0.000362 0.003672 0.014648 0.023204 0.014648 0.003672 0.000362 0.000014 0 0 0 0.000001 0.000055 0.001445 0.014648 0.058433 0.092564 0.058433 0.014648 0.001445 0.000055 0.000001 0 0 0.000001 0.000088 0.002289 0.023204 0.092564 0.146632 0.092564 0.023204 0.002289 0.000088 0.000001 0 0 0.000001 0.000055 0.001445 0.014648 0.058433 0.092564 0.058433 0.014648 0.001445 0.000055 0.000001 0 0 0 0.000014 0.000362 0.003672 0.014648 0.023204 0.014648 0.003672 0.000362 0.000014 0 0 0 0 0.000001 0.000036 0.000362 0.001445 0.002289 0.001445 0.000362 0.000036 0.000001 0 0 0 0 0 0.000001 0.000014 0.000055 0.000088 0.000055 0.000014 0.000001 0 0 0 0 0 0 0 0 0.000001 0.000001 0.000001 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</Coefs></Kernel>'
            )
            with open(os.path.join(path, "dem_blur_13x13.vrt"), "wt") as file:
                file.write(data)

            Calc(
                calc="A*B+(1-A)*C",
                A=os.path.join(path, 'tpi_norm.tif'),
                B=os.path.join(path, 'dem_blur_3x3.vrt'),
                C=os.path.join(path, 'dem_blur_13x13.vrt'),
                outfile=os.path.join(path, 'merged.tif'),
                overwrite=True
            )

        feedback.setProgress(int((self.progresso + 1.0) * self.status_total))

    def icon(self):
        cmd_folder = os.path.dirname(__file__)
        icon = QIcon(os.path.join(cmd_folder, 'logo.png'))
        return icon

    def name(self):

        return 'Curva de Nivel'

    def displayName(self):

        return self.tr(self.name())

    def group(self):

        return self.tr(self.groupId())

    def groupId(self):

        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CurvaDeNivelAlgorithm()
